import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a" },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 24 },
  logo: { width: 28, height: 28 },
  brand: { fontSize: 14, fontWeight: 700 },
  meta: { fontSize: 9, color: "#666666" },
  title: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#555555", marginBottom: 20 },
  scoreRow: { flexDirection: "row", gap: 16, marginBottom: 24 },
  scoreCard: { flex: 1, padding: 12, backgroundColor: "#f5f5f5", borderRadius: 4 },
  scoreLabel: { fontSize: 9, color: "#666666", marginBottom: 4 },
  scoreValue: { fontSize: 22, fontWeight: 700 },
  sectionTitle: { fontSize: 13, fontWeight: 700, marginTop: 20, marginBottom: 10 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#e5e5e5" },
  rowLabel: { flex: 1 },
  rowValue: { fontWeight: 700 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#999999", textAlign: "center" },
});

export interface ReportPdfData {
  brandName: string;
  brandLogoUrl: string | null;
  projectName: string;
  reportTypeLabel: string;
  periodStart: string;
  periodEnd: string;
  overallScore: { visibilityScore: number; mentionFrequency: number; shareOfVoice: number };
  competitorComparison: { name: string; score: number; isYou: boolean }[];
  citations: { domain: string; sourceType: string; mentions: number }[];
}

export function ReportPdfDocument({ data }: { data: ReportPdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}>
            {data.brandLogoUrl && <Image src={data.brandLogoUrl} style={styles.logo} />}
            <Text style={styles.brand}>{data.brandName}</Text>
          </View>
          <Text style={styles.meta}>
            {data.periodStart} – {data.periodEnd}
          </Text>
        </View>

        <Text style={styles.title}>{data.reportTypeLabel} AI Visibility Report</Text>
        <Text style={styles.subtitle}>{data.projectName}</Text>

        <View style={styles.scoreRow}>
          <View style={styles.scoreCard}>
            <Text style={styles.scoreLabel}>AI Visibility Score</Text>
            <Text style={styles.scoreValue}>{Math.round(data.overallScore.visibilityScore)}/100</Text>
          </View>
          <View style={styles.scoreCard}>
            <Text style={styles.scoreLabel}>Mention Frequency</Text>
            <Text style={styles.scoreValue}>{Math.round(data.overallScore.mentionFrequency)}%</Text>
          </View>
          <View style={styles.scoreCard}>
            <Text style={styles.scoreLabel}>Share of Voice</Text>
            <Text style={styles.scoreValue}>{Math.round(data.overallScore.shareOfVoice)}%</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Competitor comparison</Text>
        {data.competitorComparison.map((c) => (
          <View style={styles.row} key={c.name}>
            <Text style={[styles.rowLabel, c.isYou ? { fontWeight: 700 } : {}]}>{c.name}</Text>
            <Text style={styles.rowValue}>{Math.round(c.score)}</Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>Top cited domains</Text>
        {data.citations.slice(0, 10).map((c) => (
          <View style={styles.row} key={c.domain}>
            <Text style={styles.rowLabel}>
              {c.domain} ({c.sourceType})
            </Text>
            <Text style={styles.rowValue}>{c.mentions}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          AI Visibility Score is a statistical estimate from repeated LLM sampling, not a fixed rank — see your
          dashboard for full methodology. Generated by {data.brandName}.
        </Text>
      </Page>
    </Document>
  );
}
