import type { BacktestSummary, GamePick, Lineup } from "@/lib/api";

const later = (hours: number) => new Date(Date.now() + hours * 3600_000).toISOString();

export const DEMO_PICKS: GamePick[] = [
  // NFL
  {
    game_id: 101,
    sport: "NFL",
    commence_time: later(4),
    home_team: "KC",
    away_team: "BUF",
    pick_side: "home",
    pick_team: "KC",
    model_prob: 0.58,
    market_prob: 0.55,
    elo_prob: 0.57,
    edge_pp: 3.2,
    confidence: 0.74,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  {
    game_id: 102,
    sport: "NFL",
    commence_time: later(6),
    home_team: "DET",
    away_team: "PHI",
    pick_side: "away",
    pick_team: "PHI",
    model_prob: 0.54,
    market_prob: 0.5,
    elo_prob: 0.52,
    edge_pp: 2.6,
    confidence: 0.66,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  {
    game_id: 103,
    sport: "NFL",
    commence_time: later(8),
    home_team: "SF",
    away_team: "DAL",
    pick_side: "home",
    pick_team: "SF",
    model_prob: 0.63,
    market_prob: 0.6,
    elo_prob: 0.61,
    edge_pp: 3.8,
    confidence: 0.79,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  // CFB
  {
    game_id: 201,
    sport: "CFB",
    commence_time: later(5),
    home_team: "UGA",
    away_team: "ALA",
    pick_side: "home",
    pick_team: "UGA",
    model_prob: 0.56,
    market_prob: 0.53,
    elo_prob: 0.55,
    edge_pp: 2.9,
    confidence: 0.7,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  {
    game_id: 202,
    sport: "CFB",
    commence_time: later(7),
    home_team: "OHIO",
    away_team: "ORE",
    pick_side: "home",
    pick_team: "OHIO",
    model_prob: 0.59,
    market_prob: 0.56,
    elo_prob: 0.58,
    edge_pp: 3.4,
    confidence: 0.73,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  {
    game_id: 203,
    sport: "CFB",
    commence_time: later(9),
    home_team: "TEX",
    away_team: "MICH",
    pick_side: "home",
    pick_team: "TEX",
    model_prob: 0.61,
    market_prob: 0.58,
    elo_prob: 0.6,
    edge_pp: 3.1,
    confidence: 0.72,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  // NBA
  {
    game_id: 1,
    sport: "NBA",
    commence_time: later(3),
    home_team: "OKC",
    away_team: "DEN",
    pick_side: "home",
    pick_team: "OKC",
    model_prob: 0.62,
    market_prob: 0.57,
    elo_prob: 0.64,
    edge_pp: 4.2,
    confidence: 0.78,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  {
    game_id: 2,
    sport: "NBA",
    commence_time: later(5),
    home_team: "BOS",
    away_team: "NYK",
    pick_side: "home",
    pick_team: "BOS",
    model_prob: 0.58,
    market_prob: 0.53,
    elo_prob: 0.59,
    edge_pp: 3.1,
    confidence: 0.71,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
];

export const DEMO_LINEUPS: Lineup[] = [
  {
    rank: 1,
    platform: "prizepicks",
    sport: "NFL",
    expected_value: 0.16,
    win_prob: 0.2,
    salary_used: 5,
    deep_link: "https://app.prizepicks.com/",
    picks: [
      { player_name: "Patrick Mahomes", team_abbr: "KC", stat_type: "Pass Yards", line: 275.5, side: "over", model_mean: 285.0, hit_prob: 0.57, edge: 0.07 },
      { player_name: "Josh Allen", team_abbr: "BUF", stat_type: "Pass Yards", line: 268.5, side: "over", model_mean: 276.0, hit_prob: 0.55, edge: 0.05 },
      { player_name: "Christian McCaffrey", team_abbr: "SF", stat_type: "Rush Yards", line: 85.5, side: "over", model_mean: 92.0, hit_prob: 0.56, edge: 0.06 },
      { player_name: "A.J. Brown", team_abbr: "PHI", stat_type: "Receiving Yards", line: 78.5, side: "over", model_mean: 84.0, hit_prob: 0.54, edge: 0.04 },
      { player_name: "CeeDee Lamb", team_abbr: "DAL", stat_type: "Receptions", line: 6.5, side: "over", model_mean: 7.1, hit_prob: 0.53, edge: 0.03 },
    ],
  },
  {
    rank: 1,
    platform: "prizepicks",
    sport: "CFB",
    expected_value: 0.14,
    win_prob: 0.19,
    salary_used: 5,
    deep_link: "https://app.prizepicks.com/",
    picks: [
      { player_name: "Carson Beck", team_abbr: "UGA", stat_type: "Pass Yards", line: 240.5, side: "over", model_mean: 248.0, hit_prob: 0.56, edge: 0.06 },
      { player_name: "Will Howard", team_abbr: "OHIO", stat_type: "Pass Yards", line: 230.5, side: "over", model_mean: 238.0, hit_prob: 0.55, edge: 0.05 },
      { player_name: "Jeremiah Smith", team_abbr: "OHIO", stat_type: "Receiving Yards", line: 88.5, side: "over", model_mean: 95.0, hit_prob: 0.57, edge: 0.07 },
      { player_name: "Quinn Ewers", team_abbr: "TEX", stat_type: "Pass Yards", line: 245.5, side: "under", model_mean: 236.0, hit_prob: 0.54, edge: 0.04 },
      { player_name: "Nicholas Singleton", team_abbr: "PSU", stat_type: "Rush Yards", line: 95.5, side: "over", model_mean: 102.0, hit_prob: 0.53, edge: 0.03 },
    ],
  },
  {
    rank: 1,
    platform: "prizepicks",
    sport: "NBA",
    expected_value: 0.18,
    win_prob: 0.22,
    salary_used: 5,
    deep_link: "https://app.prizepicks.com/",
    picks: [
      { player_name: "Shai Gilgeous-Alexander", team_abbr: "OKC", stat_type: "Points", line: 31.5, side: "over", model_mean: 33.1, hit_prob: 0.58, edge: 0.08 },
      { player_name: "Jayson Tatum", team_abbr: "BOS", stat_type: "Rebounds", line: 8.5, side: "over", model_mean: 9.2, hit_prob: 0.56, edge: 0.06 },
      { player_name: "Nikola Jokic", team_abbr: "DEN", stat_type: "Assists", line: 9.5, side: "under", model_mean: 8.9, hit_prob: 0.55, edge: 0.05 },
      { player_name: "Jalen Brunson", team_abbr: "NYK", stat_type: "Points", line: 26.5, side: "over", model_mean: 27.8, hit_prob: 0.54, edge: 0.04 },
      { player_name: "Anthony Edwards", team_abbr: "MIN", stat_type: "Pts+Rebs+Asts", line: 38.5, side: "over", model_mean: 40.2, hit_prob: 0.53, edge: 0.03 },
    ],
  },
];

export const DEMO_BACKTEST: BacktestSummary = {
  total_picks: 612,
  graded_picks: 540,
  wins: 312,
  win_rate: 0.578,
  avg_edge_pp: 3.2,
  avg_model_prob: 0.59,
  positive_ev: true,
  launch_ready: true,
  calibration: [
    { bucket: "50-55%", predicted: 0.525, actual: 0.51, count: 90 },
    { bucket: "55-60%", predicted: 0.575, actual: 0.58, count: 120 },
    { bucket: "60-65%", predicted: 0.625, actual: 0.61, count: 140 },
    { bucket: "65-70%", predicted: 0.675, actual: 0.66, count: 110 },
    { bucket: "70-75%", predicted: 0.725, actual: 0.71, count: 80 },
  ],
  notes: "Demo calibration across NBA / NFL / CFB — connect live feeds for production EV.",
};
