import type { BacktestSummary, GamePick, Lineup } from "@/lib/api";

const later = (hours: number) => new Date(Date.now() + hours * 3600_000).toISOString();

export const DEMO_PICKS: GamePick[] = [
  {
    game_id: 1,
    commence_time: later(3),
    home_team: "OKC",
    away_team: "DEN",
    pick_side: "home",
    pick_team: "OKC",
    model_prob: 0.62,
    market_prob: 0.57,
    elo_prob: 0.64,
    edge_pp: 4.2,
    confidence: 0.78,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  {
    game_id: 2,
    commence_time: later(5),
    home_team: "BOS",
    away_team: "NYK",
    pick_side: "home",
    pick_team: "BOS",
    model_prob: 0.58,
    market_prob: 0.53,
    elo_prob: 0.59,
    edge_pp: 3.1,
    confidence: 0.71,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
  {
    game_id: 3,
    commence_time: later(6),
    home_team: "MIN",
    away_team: "PHX",
    pick_side: "away",
    pick_team: "PHX",
    model_prob: 0.55,
    market_prob: 0.51,
    elo_prob: 0.54,
    edge_pp: 2.4,
    confidence: 0.63,
    deep_link: "https://robinhood.com/us/en/prediction-markets/",
    status: "scheduled",
  },
];

export const DEMO_LINEUPS: Lineup[] = [
  {
    rank: 1,
    platform: "prizepicks",
    expected_value: 0.18,
    win_prob: 0.22,
    salary_used: 5,
    deep_link: "https://app.prizepicks.com/",
    picks: [
      {
        player_name: "Shai Gilgeous-Alexander",
        team_abbr: "OKC",
        stat_type: "Points",
        line: 31.5,
        side: "over",
        model_mean: 33.1,
        hit_prob: 0.58,
        edge: 0.08,
      },
      {
        player_name: "Jayson Tatum",
        team_abbr: "BOS",
        stat_type: "Rebounds",
        line: 8.5,
        side: "over",
        model_mean: 9.2,
        hit_prob: 0.56,
        edge: 0.06,
      },
      {
        player_name: "Nikola Jokic",
        team_abbr: "DEN",
        stat_type: "Assists",
        line: 9.5,
        side: "under",
        model_mean: 8.9,
        hit_prob: 0.55,
        edge: 0.05,
      },
      {
        player_name: "Jalen Brunson",
        team_abbr: "NYK",
        stat_type: "Points",
        line: 26.5,
        side: "over",
        model_mean: 27.8,
        hit_prob: 0.54,
        edge: 0.04,
      },
      {
        player_name: "Anthony Edwards",
        team_abbr: "MIN",
        stat_type: "Pts+Rebs+Asts",
        line: 38.5,
        side: "over",
        model_mean: 40.2,
        hit_prob: 0.53,
        edge: 0.03,
      },
    ],
  },
];

export const DEMO_BACKTEST: BacktestSummary = {
  total_picks: 612,
  graded_picks: 540,
  wins: 312,
  win_rate: 0.578,
  avg_edge_pp: 3.2,
  avg_model_prob: 0.59,
  positive_ev: true,
  launch_ready: true,
  calibration: [
    { bucket: "50-55%", predicted: 0.525, actual: 0.51, count: 90 },
    { bucket: "55-60%", predicted: 0.575, actual: 0.58, count: 120 },
    { bucket: "60-65%", predicted: 0.625, actual: 0.61, count: 140 },
    { bucket: "65-70%", predicted: 0.675, actual: 0.66, count: 110 },
    { bucket: "70-75%", predicted: 0.725, actual: 0.71, count: 80 },
  ],
  notes: "Demo calibration — connect live feeds for production EV.",
};
